In [34]:
import pandas as pd
import numpy as np

In [35]:
# Load and check data
# df = pd.read_csv("/Users/avril/Desktop/DMT/DMT_Assignment_1/data/cleaned/dataset_mood_smartphone_cleaned.csv", parse_dates=["date"])
df = pd.read_csv("../data/cleaned/dataset_mood_smartphone_cleaned.csv", parse_dates=["date"])

print(df.dtypes)
df.head()

id                                 str
date                    datetime64[us]
activity                       float64
appCat.builtin                 float64
appCat.communication           float64
appCat.entertainment           float64
appCat.finance                 float64
appCat.game                    float64
appCat.office                  float64
appCat.other                   float64
appCat.social                  float64
appCat.travel                  float64
appCat.unknown                 float64
appCat.utilities               float64
appCat.weather                 float64
call                             int64
circumplex.arousal             float64
circumplex.valence             float64
mood                           float64
screen                         float64
sms                              int64
dtype: object

,id,date,activity,appCat.builtin,appCat.communication,appCat.entertainment,appCat.finance,appCat.game,appCat.office,appCat.other,...,appCat.travel,appCat.unknown,appCat.utilities,appCat.weather,call,circumplex.arousal,circumplex.valence,mood,screen,sms
0,AS14.01,2014-02-17,0.080856,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2,-0.245213,0.755012,7.075177,0.0,0
1,AS14.01,2014-02-18,0.080856,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1,-0.245213,0.755012,7.075177,0.0,0
2,AS14.01,2014-02-19,0.080856,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,7,-0.245213,0.755012,7.075177,0.0,2
3,AS14.01,2014-02-20,0.080856,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2,-0.245213,0.755012,7.075177,0.0,3
4,AS14.01,2014-02-21,0.080856,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0,-0.245213,0.755012,7.075177,0.0,1

In [36]:
df["date"] = pd.to_datetime(df["date"], errors="coerce")
df.head()

,id,date,activity,appCat.builtin,appCat.communication,appCat.entertainment,appCat.finance,appCat.game,appCat.office,appCat.other,...,appCat.travel,appCat.unknown,appCat.utilities,appCat.weather,call,circumplex.arousal,circumplex.valence,mood,screen,sms
0,AS14.01,2014-02-17,0.080856,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2,-0.245213,0.755012,7.075177,0.0,0
1,AS14.01,2014-02-18,0.080856,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1,-0.245213,0.755012,7.075177,0.0,0
2,AS14.01,2014-02-19,0.080856,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,7,-0.245213,0.755012,7.075177,0.0,2
3,AS14.01,2014-02-20,0.080856,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2,-0.245213,0.755012,7.075177,0.0,3
4,AS14.01,2014-02-21,0.080856,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0,-0.245213,0.755012,7.075177,0.0,1

# Feature engineering

In [37]:
# Replace valence and arousal with product as 'emotion'
df['emotion'] = df['circumplex.valence'] * df['circumplex.arousal']

df["count_call_and_sms"] = ( df["call"] + df["sms"])

df = df.drop(columns=['circumplex.valence', 'circumplex.arousal', 'sms', 'call'])
df.head()

,id,date,activity,appCat.builtin,appCat.communication,appCat.entertainment,appCat.finance,appCat.game,appCat.office,appCat.other,appCat.social,appCat.travel,appCat.unknown,appCat.utilities,appCat.weather,mood,screen,emotion,count_call_and_sms
0,AS14.01,2014-02-17,0.080856,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.075177,0.0,-0.185139,2
1,AS14.01,2014-02-18,0.080856,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.075177,0.0,-0.185139,1
2,AS14.01,2014-02-19,0.080856,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.075177,0.0,-0.185139,9
3,AS14.01,2014-02-20,0.080856,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.075177,0.0,-0.185139,5
4,AS14.01,2014-02-21,0.080856,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.075177,0.0,-0.185139,1

In [38]:
# Replace individual "appCat" features with aggregated cateories
app_cols = [c for c in df.columns if c.startswith("appCat.")]
df["total_app_use"] = df[app_cols].fillna(0).sum(axis=1)

def safe_ratio(numerator, denominator):
    return numerator.where(denominator > 0, 0.0) / denominator.where(denominator > 0, 1.0)

df["social_ratio"] = safe_ratio(
    df["appCat.social"] + df["appCat.communication"],
    df["total_app_use"]
)

df["productive_ratio"] = safe_ratio(
    df["appCat.finance"] + df["appCat.office"] + df["appCat.utilities"],
    df["total_app_use"]
)

df["passive_entertainment_ratio"] = safe_ratio(
    df["appCat.entertainment"] + df["appCat.game"],
    df["total_app_use"]
)

df["adventure_ratio"] = safe_ratio(
    df["appCat.travel"] + df["appCat.weather"],
    df["total_app_use"]
)

df["miscellaneous_ratio"] = safe_ratio(
    df["appCat.other"] + df["appCat.unknown"] + df["appCat.utilities"],
    df["total_app_use"]
)

df = df.drop(columns=app_cols)
df.head()

,id,date,activity,mood,screen,emotion,count_call_and_sms,total_app_use,social_ratio,productive_ratio,passive_entertainment_ratio,adventure_ratio,miscellaneous_ratio
0,AS14.01,2014-02-17,0.080856,7.075177,0.0,-0.185139,2,0.0,0.0,0.0,0.0,0.0,0.0
1,AS14.01,2014-02-18,0.080856,7.075177,0.0,-0.185139,1,0.0,0.0,0.0,0.0,0.0,0.0
2,AS14.01,2014-02-19,0.080856,7.075177,0.0,-0.185139,9,0.0,0.0,0.0,0.0,0.0,0.0
3,AS14.01,2014-02-20,0.080856,7.075177,0.0,-0.185139,5,0.0,0.0,0.0,0.0,0.0,0.0
4,AS14.01,2014-02-21,0.080856,7.075177,0.0,-0.185139,1,0.0,0.0,0.0,0.0,0.0,0.0

In [39]:
df[df["total_app_use"] > df["screen"]].head()

,id,date,activity,mood,screen,emotion,count_call_and_sms,total_app_use,social_ratio,productive_ratio,passive_entertainment_ratio,adventure_ratio,miscellaneous_ratio
26,AS14.01,2014-03-21,0.087240,6.2,13984.396,0.040,6,13984.396135,0.644853,0.036063,0.065777,0.032696,0.037238
33,AS14.01,2014-03-28,0.077666,6.4,4923.489,-0.540,5,4923.489040,0.279612,0.079224,0.251007,0.159729,0.106948
36,AS14.01,2014-03-31,0.070505,7.4,8762.112,0.000,6,8762.112952,0.631374,0.023765,0.171001,0.017324,0.048005
42,AS14.01,2014-04-06,0.049669,6.5,5674.088,-0.375,4,5674.088056,0.518679,0.007199,0.046952,0.000000,0.025742
50,AS14.01,2014-04-14,0.083887,7.2,9261.666,-0.720,2,9261.666086,0.561076,0.066519,0.280599,0.002353,0.071027

In [40]:
# Add last day market for TS dataset
df_ts = df.copy()
df["is_last_day"] = (df["date"] == df["id"].map(df.groupby("id")["date"].max())).astype(int)
df[df["is_last_day"] == 1].head()

,id,date,activity,mood,screen,emotion,count_call_and_sms,total_app_use,social_ratio,productive_ratio,passive_entertainment_ratio,adventure_ratio,miscellaneous_ratio,is_last_day
71,AS14.01,2014-05-05,0.007843,7.075177,1788.73400,-0.185139,0,1744.627,0.488294,0.077882,0.182569,0.0,0.077882,1
139,AS14.02,2014-04-25,0.265355,9.000000,0.00000,-1.000000,0,0.000,0.000000,0.000000,0.000000,0.0,0.000000,1
216,AS14.03,2014-05-08,0.000000,7.603901,0.00000,-0.058889,0,0.000,0.000000,0.000000,0.000000,0.0,0.000000,1
286,AS14.05,2014-05-05,0.002491,6.333334,49.03300,-0.333333,0,48.147,0.680645,0.000000,0.107068,0.0,0.212287,1
360,AS14.06,2014-05-08,0.000000,7.000000,381.99103,-1.000000,0,381.991,0.960910,0.000000,0.039090,0.0,0.000000,1

# Aggregate entries into one per individual (id)

In [41]:
# Identify last day per individual
df_last_days = df.groupby("id")["date"].max().reset_index()
df_last_days = df.merge(df_last_days, on=["id", "date"])
df_last_days = df_last_days.rename(columns={"date": "last_date"})

# Compute average mood on the last day per individual
df_last_days_mood = (
    df_last_days.groupby("id")
                .agg({
                    "mood": "mean",
                    "last_date": "first"
                })
                .reset_index()
)
df_last_days_mood = df_last_days_mood.rename(columns={"mood": "avg_last_day_mood"})
df_last_days.head()

,id,last_date,activity,mood,screen,emotion,count_call_and_sms,total_app_use,social_ratio,productive_ratio,passive_entertainment_ratio,adventure_ratio,miscellaneous_ratio,is_last_day
0,AS14.01,2014-05-05,0.007843,7.075177,1788.73400,-0.185139,0,1744.627,0.488294,0.077882,0.182569,0.0,0.077882,1
1,AS14.02,2014-04-25,0.265355,9.000000,0.00000,-1.000000,0,0.000,0.000000,0.000000,0.000000,0.0,0.000000,1
2,AS14.03,2014-05-08,0.000000,7.603901,0.00000,-0.058889,0,0.000,0.000000,0.000000,0.000000,0.0,0.000000,1
3,AS14.05,2014-05-05,0.002491,6.333334,49.03300,-0.333333,0,48.147,0.680645,0.000000,0.107068,0.0,0.212287,1
4,AS14.06,2014-05-08,0.000000,7.000000,381.99103,-1.000000,0,381.991,0.960910,0.000000,0.039090,0.0,0.000000,1

In [42]:
# Merge last day mood back to daily dataset and filter for prior days only
df_prior_days = df.merge(df_last_days_mood[["id", "last_date"]], on="id")
df_prior_days = df_prior_days[df_prior_days['date'] < df_prior_days['last_date']]

# Compute time decay weights
decay_rate = 0.1
df_prior_days["diff_days"] = (df_prior_days["last_date"] - df_prior_days["date"]).dt.days
df_prior_days["weight"] = np.exp(-decay_rate * df_prior_days["diff_days"])

value_cols = [c for c in df_prior_days.columns if c not in ["id", "date", "last_date", "diff_days", "weight"]]
for col in value_cols:
    df_prior_days[col] = df_prior_days[col] * df_prior_days["weight"]

df_prior_days.head()

,id,date,activity,mood,screen,emotion,count_call_and_sms,total_app_use,social_ratio,productive_ratio,passive_entertainment_ratio,adventure_ratio,miscellaneous_ratio,is_last_day,last_date,diff_days,weight
0,AS14.01,2014-02-17,0.000037,0.003204,0.0,-0.000084,0.000906,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2014-05-05,77,0.000453
1,AS14.01,2014-02-18,0.000040,0.003541,0.0,-0.000093,0.000500,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2014-05-05,76,0.000500
2,AS14.01,2014-02-19,0.000045,0.003913,0.0,-0.000102,0.004978,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2014-05-05,75,0.000553
3,AS14.01,2014-02-20,0.000049,0.004325,0.0,-0.000113,0.003056,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2014-05-05,74,0.000611
4,AS14.01,2014-02-21,0.000055,0.004780,0.0,-0.000125,0.000676,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2014-05-05,73,0.000676

In [43]:
df_weighted_avg = df_prior_days.groupby("id").agg(
    **{
        col: (col, lambda x: (
            x.sum() / df_prior_days.loc[x.index[x.notna()], "weight"].sum()
            if x.notna().any() else np.nan
        ))
        for col in value_cols
    }
).reset_index()

df_non_ts = df_last_days_mood.merge(df_weighted_avg, on="id", how="left")
df_non_ts = df_non_ts.dropna(subset=['avg_last_day_mood'])
df_non_ts = df_non_ts.drop(columns=["last_date"])
df_non_ts.head()

,id,avg_last_day_mood,activity,mood,screen,emotion,count_call_and_sms,total_app_use,social_ratio,productive_ratio,passive_entertainment_ratio,adventure_ratio,miscellaneous_ratio,is_last_day
0,AS14.01,7.075177,0.075781,7.522327,7817.067169,-0.275462,2.245028,7280.181193,0.647668,0.039999,0.111057,0.013565,0.037455,0.0
1,AS14.02,9.000000,0.244542,6.606570,1421.464389,0.139487,8.394476,1391.140549,0.382078,0.000949,0.036332,0.013750,0.008949,0.0
2,AS14.03,7.603901,0.099556,7.452009,2956.751039,-0.536404,2.774058,2942.558380,0.314421,0.016701,0.477434,0.010583,0.054489,0.0
3,AS14.05,6.333334,0.050438,7.023817,4330.678731,-0.260714,2.051895,4287.663137,0.786221,0.006334,0.066931,0.000019,0.054055,0.0
4,AS14.06,7.000000,0.153710,7.090528,5563.767047,-0.210185,2.335118,5529.571291,0.693347,0.010218,0.184090,0.019625,0.018924,0.0

In [44]:
# df_ts.to_csv("/Users/avril/Desktop/DMT/DMT_Assignment_1/data/engineered/dataset_mood_smartphone_ts.csv", index=False)
# df_non_ts.to_csv("/Users/avril/Desktop/DMT/DMT_Assignment_1/data/engineered/dataset_mood_smartphone_non_ts.csv", index=False)

df_ts.to_csv("../data/engineered/dataset_mood_smartphone_ts.csv", index=False)
df_non_ts.to_csv("../data/engineered/dataset_mood_smartphone_non_ts.csv", index=False)